<?php 

/**
 * Plugin Name: Codebot Tab
 * Plugin URI:  https://codebottechnologies.com/
 * Description: Codebot Fullpage Tab
 * Version:     2.0160911
 * Author:      Leon Chux
 * Author URI:  https://leonchux.com
 * License:     GPL2
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: wporg
 * Domain Path: /languages
 */


/**
 * 
 */






function fwds_slider_deactivation() {
};
function fwds_slider_activation() {
};




// Register Session

function register_my_session(){
    if( ! session_id() ) {
        session_start();
    }
}

add_action('init', 'register_my_session');




register_activation_hook(__FILE__, 'fwds_slider_activation');
register_deactivation_hook(__FILE__, 'fwds_slider_deactivation');


// bind wordpress ajax_url to our function
add_action('wp_ajax_fpt_ajax','fpt_ajax');
add_action('wp_ajax_no_priv_fpt_ajax','fpt_ajax');

// bind wordpress ajax_file_url to our function
add_action('wp_ajax_fpt_file','fpt_file_upload');
add_action('wp_ajax_no_priv_fpt_file','fpt_file_upload');






// Handle file upload

function fpt_file_upload() {

  // $allowedTypes = array(IMAGETYPE_PNG, IMAGETYPE_JPEG,);
  // $detectedType = exif_imagetype($_FILES['file']['tmp_name']);

$file_extension = pathinfo($_FILES["file"]["name"], PATHINFO_EXTENSION);
$allowed_image_extension = array(
        "png",
        "jpg",
        "jpeg",
         "JPEG",
         "JPG"
    );
// (in_array($detectedType, $allowedTypes))

  if (in_array($file_extension, $allowed_image_extension)) {
    



      if (($_FILES["file"]["size"] < 20971520)||($_FILES["file"]["size"] == 20971520)) {


          // These files need to be included as dependencies when on the front end.
            require_once( ABSPATH . 'wp-admin/includes/image.php' );
            require_once( ABSPATH . 'wp-admin/includes/file.php' );
            require_once( ABSPATH . 'wp-admin/includes/media.php' );
            
            // Let WordPress handle the upload.
            // Remember, 'my_image_upload' is the name of our file input in our form above.
            $attachment_id = media_handle_upload( 'file', "image" );
            if ( is_wp_error( $attachment_id ) ) {
                echo "error";
              } else {
               echo"done";
              }








         

          // if ( ! function_exists( 'wp_handle_upload' ) ) {
          //     require_once( ABSPATH . 'wp-admin/includes/file.php' );
          // }

          // $uploadedfile = $_FILES['file'];

          // $upload_overrides = array( 'test_form' => false );

          // $movefile = wp_handle_upload( $uploadedfile, $upload_overrides );

          // if ( $movefile && ! isset( $movefile['error'] ) ) {
          //     echo "File is valid, and was successfully uploaded.\n";
          //     // var_dump( $movefile );
          // } else {
          //     /**
          //      * Error generated by _wp_handle_upload()
          //      * @see _wp_handle_upload() in wp-admin/includes/file.php
          //      */
          //     echo $movefile['error'];
          // }


      }
      else{

        echo "toobig";}
      

  } 
  else {
    echo "invalidformat";
  }
  

  
 exit;
 
}





// Handles ajax request 
// Collects form data and assigns them to session array
// Send contents of array as email
// destroys session
// redirects user to homepage

function fpt_ajax()
{
  check_ajax_referer('fpt-nonce','security');
  
  $formData=array();
  parse_str($_POST['data'],$formData);
 
  foreach ($formData as $key => $value) {
    if(!empty($formData[$key])){
         $_SESSION["$key"]=$value;


    }
          
  }

  if (isset($_SESSION['key1']) && isset($_SESSION['key2']) && isset($_SESSION['key3'])) {

   

    
    $to= $_SESSION['adminemail']; 
    
    $subject = 'New Codebot Order';
    $headers = array('Content-Type: text/html; charset=UTF-8');
    $body = '<table><thead>
  <tr><th>Field</th>
    <th>value</th>
  </tr> </thead><tbody>';



  foreach ($_SESSION as $key => $value) {
    // global $body;
    $body.= '<tr><td>';
    $body.= $key;
    $body.='</td><td>';
    $body.=$value;
    $body.= '</td></tr>';
  }

  $body.='</tbody></table>';



  /**
   * Display errors
   */
  // if ( ! function_exists('debug_wpmail') ) :
  //   function debug_wpmail( $result = false ) {
  //     if ( $result )
  //       return;
  //     global $ts_mail_errors, $phpmailer;
  //     if ( ! isset($ts_mail_errors) )
  //       $ts_mail_errors = array();
  //     if ( isset($phpmailer) )
  //       $ts_mail_errors[] = $phpmailer->ErrorInfo;
  //     print_r('<pre>');
  //     print_r($ts_mail_errors);
  //     print_r('</pre>');
  //   }
  // endif;

  $res= wp_mail( $to, $subject, $body, $headers );
  // debug_wpmail($res);



// signal end of request to ajax function in frontend
    echo "true";



   
    session_destroy();

  } else {
   echo "not set";
   

  }
  

  
   

 
  exit;
}






function fwds_display_slider($atts, $content = null) {

  $ordertype = shortcode_atts( array(
    'ordertype' => 'default',
    'to'=>'sales@codebottechnologies.com',
  ), $atts );


  $_SESSION['ordertype']=$ordertype['ordertype'];
  $_SESSION['adminemail']=$ordertype['to'];


  
$site = require_once "test.php";

$url=wp_upload_dir();

print_r($url);
print_r($url['subdir']);
 

  
}

add_shortcode("codebot_tab", "fwds_display_slider");





?>